#ifndef GENERIC__INTERFACES_GENERIC_GENERIC_CONSTANTS_H
#define GENERIC__INTERFACES_GENERIC_GENERIC_CONSTANTS_H 

#include "GenericManagerDefinition.h"

extern struct GenericManager g_NullGenericManager;

extern struct GenericManager g_CharGenericManager;
extern struct GenericManager g_ShortGenericManager;
extern struct GenericManager g_IntGenericManager;
extern struct GenericManager g_LongGenericManager;
extern struct GenericManager g_LongLongGenericManager;

extern struct GenericManager g_UnsignedCharGenericManager;
extern struct GenericManager g_UnsignedShortGenericManager;
extern struct GenericManager g_UnsignedIntGenericManager;
extern struct GenericManager g_UnsignedLongGenericManager;
extern struct GenericManager g_UnsignedLongLongGenericManager;

extern struct GenericManager g_FloatGenericManager;
extern struct GenericManager g_DoubleGenericManager;
extern struct GenericManager g_LongDoubleGenericManager;

extern struct GenericManager g_PointerGenericManager;
extern struct GenericManager g_CStringGenericManager;

extern struct GenericManager g_SizeGenericManager;

extern struct GenericManager g_ArrayGenericManager;

extern struct GenericManager g_GenericManagerGenericManager;

#endif //GENERIC__INTERFACES_GENERIC_GENERIC_CONSTANTS_H