#ifndef FUNDAMENTAL__FUNDAMENTAL_SIZE_CONSTANTS_H
#define FUNDAMENTAL__FUNDAMENTAL_SIZE_CONSTANTS_H

#include "SizeDefinition.h"

extern const Size SIZE_MINIMUM;
extern const Size SIZE_MAXIMUM;

#endif //FUNDAMENTAL__FUNDAMENTAL_SIZE_CONSTANTS_H