#ifndef CALLBACK__INTERFACES_CALLBACK_CALLBACK_H
#define CALLBACK__INTERFACES_CALLBACK_CALLBACK_H

#include "CallbackDefinition.h"
#include "CallbackFunctions.h"

#endif //CALLBACK__INTERFACES_CALLBACK_CALLBACK_H